# NEVER edit config-version; it is used to verify the file schema.
config-version: 1

# How often player profiles are autosaved, in seconds.
# 300 seconds = 5 minutes.
profile-auto-save-interval: 300
