name: UltimateModerationPlus
main: me.xaxis.ultimatemoderation.UltimateModeration
version: 0.0.1
api-version: 1.20
commands:
  spy:
    description: Spy on a player
    usage: /spy <player_name>
  staffchat:
    description: Talk in staff chat
    usage: /staffchat
    aliases:
      - sc